version: '3'

tasks:
  default:
    desc: "The default task" 
    cmds:
      - clear
      - task: test-go

  run:
    cmds:
      - go run .

  build:
    cmds:
      - CGO_ENABLED=0 go build .
  
  test-alpine:
    deps:
      - build
    cmds:
      - docker build -t test-alpine -f ./tests/alpine/Dockerfile .
      - docker run -it --rm test-alpine mirctl

  test-pip:
    deps:
      - build
    cmds:
      - docker build -t test-pip -f ./tests/pip/Dockerfile .
      - docker run -it --rm test-pip mirctl --repos pip,alpine

  test-go:
    deps:
      - build
    cmds:
      - docker build -t test-go -f ./tests/go/Dockerfile .
      - docker run -it --rm test-go mirctl --repos go

  test-arch:
    deps:
      - build
    cmds:
      - docker build -t test-arch -f ./tests/arch/Dockerfile .
      - docker run -it --rm test-arch mirctl --repos arch